Gargaj/Bonzomatic

platform_sdl/Renderer.cpp, platform_x11/Timer.cpp
Some changes are needed to compile on at least OSX 10.8.5. There are some Makefile changes required to build with the existing Makefile, but, those will go into another PR.
- clock_gettime() doesn't exist in MACH, so use the clock_get_time()
- nullptr_t is not declared in older stdc++ for jsonxx
- OpenGL libraries on OSX are located in OpenGL/*
=> Add some Apple-specific code to allow compilation

Makefile, platform_sdl/MIDI.cpp, platform_sdl/Misc.cpp
This basically only adds files in platform_sdl, so it should not affect builds on other platforms.
Of course, a working midi implementation on linux would be nice, but a dummy is still better than not compiling at all.
=> Added dummy midi and misc-functions to platform_sdl, fixing linux build.

src/platform_x11/Clipboard.cpp
This commit adds clipboard support on X11 platforms via GLFW.
Note that since the clipboard implementation is purely based on GLFW, it may make sense to move it under platform_glfw instead, and have the MacOS X platform also use this (as well as possibly the Windows / GLFW platform). As I don't have access to the corresponding development environments, I kept the amount of changes as small as possible and focused on X11 instead.
=> Add clipboard support for X11

CMakeLists.txt, src/main.cpp
Under Linux, Bonzomatic wants to use the following font `/usr/share/fonts/corefonts/cour.ttf`.
It seems its installation path depends in not stable over distributions/versions.
This patch use the font `/usr/share/fonts/truetype/msttcorefonts/cour.ttf` if the initial one does not exist
=> Change Linux font path if required

README.md, src/main.cpp
to resolve problems with using F11 on Mac
=> Add Ctrl/Cmd-f to hide shader overlay

CMakeLists.txt, src/platform_glfw/Renderer.cpp, src/platform_osx/SetupDialog.cpp
Fullscreen modes are glitchy and dont guarantee obtaining requested resolution.
A few fixes are used to reset nWidth/nHeight and settings values to actual obtained resolution so that the interface is always working correctly whatever we get.
The dialog has 2 manually forced resolutions in the list: FullHD and HDReady. We also added whatever was eventually set in the 'config.json' so that users can manually add and try resolutions.
=> Add resolution dialog for MacOS and misc fullscreen fixes

README.md
Upon attempting a build on my Debian machine, I noticed GL/glu.h could not be found. After installing libglu1-mesa-dev the build worked. I added this requirement to README.md.
=> Added build requirement for GNU/Linux.

src/main.cpp
There was a recently introduced bug where, at least in Windows, it no longer used the font specified in `config.json`. This bugfix rectifies this issue.
=> Fix font Windows

CMakeLists.txt, src/Platform.cpp, src/Renderer.h, src/main.cpp, src/platform_glfw/Renderer.cpp, src/platform_osx/TouchBar.mm, src/platform_x11/Timer.cpp
Let linux binary be lowercase.
Also delete the line setting CMake Module Path. It was pointing to a subdirectory we dont have anymore and was meant to help finding SDL2, which we removed.
=> Keep the mac app bundle and windows exe name clean

src/platform_w32_dx11/Renderer.cpp
Not sure how I got it to work before!  Anyway, this is the DX11 counterpart to the DX9 change in 7c927ba8a79f50e12373b1e5eb57ecf9b96d1230.
=> Compile DX11 successfully on mingw32

.gitignore, src/ShaderEditor.cpp
There are still 57 warnings in the glfw library but that's mainly because OpenGL is now deprecated. This PR fixes the remaining warning in Bonzomatic.
It also adds .DS_Store to .gitignore because Macs will keep adding this file to folders and we don't want to commit it.
=> Fix final warning in Xcode 10 and add .DS_Store to .gitignore

README.md, src/platform_x11/Misc.cpp
For non programmers it's not obvious how to compile using cmake (put dot as parameter).
The font's paths are also strange. It there is a linux distribution that have those paths then I will just add new paths instead of changing the old.
=> Linux fonts fix (Ubuntu at last) and readme for building under Linux

src/platform_x11/Misc.cpp
The fonts listed in Misc.cpp weren't available by default on Ubuntu 16.04.  This adds in the UbuntuMono-R.ttf monospace font.
=> Added default ubuntu Mono font to Misc.cpp

src/ShaderEditor.cpp, src/ShaderEditor.h
Whitespaces do not count as empty here, so if a previous line contains whitespaces it will be taken into account and indentation will be set to that.
=> Preserve indentation of the last non-empty line

README.md, src/platform_osx/TouchBar.mm
Make the touchbar use the standard keyEventBuffer of the Renderer directly instead of trying some hazardous sending of keys to the process.
Wasn't working on 10.14, now it does :D
=> [macOS] Fix Touchbar

CMakeLists.txt, README.md, src/ShaderEditor.cpp, src/ShaderEditor.h, src/main.cpp
Indentation support can be set to `smart` (default), `preserve` or `none` in the `gui` section of the config file.
Readme file has been updated accordingly.
Heavily based on SciTe official implementation.
=> Smart indentation support

src/platform_glfw/Renderer.cpp
If attribute is not present, don't try to apply it.
This fixes annoying stream of Mesa complaints in terminal like (thousands of these):
```
Mesa: User error: GL_INVALID_VALUE in glVertexAttribPointerARB(idx)
Mesa: User error: GL_INVALID_VALUE in glEnableVertexAttribArray(index)
Mesa: User error: GL_INVALID_VALUE in glDisableVertexAttribArray(index)
Mesa: User error: GL_INVALID_VALUE in glVertexAttribPointerARB(idx)
Mesa: User error: GL_INVALID_VALUE in glEnableVertexAttribArray(index)
Mesa: User error: GL_INVALID_VALUE in glDisableVertexAttribArray(index)
```
=> fix incorrect use of invalid attributes

src/platform_glfw/Renderer.cpp
Added one line, setting GLFW_AUTO_ICONIFY to GL_FALSE (default is GL_TRUE).
This prevents GLFW from minimizing on loss of focus, when used in fullscreen mode.
Very useful on multi-monitor setups:
GLFW-Bonzomatic can be used in fullscreen mode without minimizing, when doing something else in another window on another monitor.
Without this change, GLFW-Bonzomatic has to be run with fullscreen:false in config.json in a window to prevent minimization.
Only tested on Linux (where GLFW is the only option!) - should work on other platforms, too.
=> Prevent fullscreen window minimize on focus loss

CMakeLists.txt, data/macosx/MacOSXBundleInfo.plist.in
Fixes a crash with PR #108
The custom plist was only used when retina support was checked, resulting in a missing key and an app crash (lack of mandatory message).
Also remove retina option from cmake. It makes no sense since it messes all the scintilla mouse selection and doesn't mirror the resolution selection (by nature). If people want to go HiDpi, they better request for a high resolution and have their wish come true.
Fake supporting HiDpi for a better window UI appearance in windowed mode.
=> The custom plist is mandatory for mic access

README.md, src/Renderer.h, src/main.cpp
Precision trackpads sometimes have slower scrolls, especially on GLFW.
This gives some control on speed (and direction in case one wants to invert scrolls) via simple factors.
Note: Had to change MouseEvent to capture float values and only convert to int after the factor is applied. It should not impact the clicks since integer values should be represented just as fine with floats.
=> Custom scroll speed via config.json

src/platform_glfw/Renderer.cpp
Useful for figuring out if a version of OpenGL isn't available, or other weird errors.
=> Add shader error to 'vertex shader compilation failed' msg

src/ShaderEditor.cpp, src/platform_w32_common/Clipboard.cpp
Fixes crashes on clipboard handling.
Also don't paste when there's nothing to paste.
This needs peer review as I'm not a windows specialist, but this looks way safer and indeed fixes crashes I experienced.
=> Make the clipboard on windows great again

src/platform_osx/Misc.mm
Added new file location for `Courier New` on Catalina. Alternative fix to #133.
=> Added new default font location for OSX Catalina (fixes #117)

src/platform_x11/Misc.cpp
fixes #144
I encountered this when I added gtk to the build in a different branch. idk why it's happening here, but it fixes it
=> Set locale to be 'C' to fix weird arrow key bug

src/platform_x11/Misc.cpp
Hi! I noticed that `postExitCmd` wasn't doing anything on Linux when I passed it a command, added a `system` call to run `postExitCmd`.
=> Run postExitCmd for Linux

src/ShaderEditor.cpp
Addresses a minor flaw in the indent handling code, which meant that setting indent mode to "none" would still act as though it was using "smart" indent rules.
=> Fix none-indent behaving as though smart-indent were enabled

CMakeLists.txt
Without this change, cmake would build a binary, but not an .app bundle.
Launching the binary would result in a crash.
With this change, a working .app file is built.
#revision2021
=> cmake: explicitly enable building a mac bundle

README.md
I've added a couple of lines of text in the readme with an example that works for Linux and OSX as well as a clarification to make sure it runs on exit.
=> Updating readme with text for non-windows platforms

CMakeLists.txt
- Use dummy MIDI implementation on OpenBSD
- Do not link against asound on OpenBSD
=> Do not use ALSA on OpenBSD

CMakeLists.txt
This fixes building Bonzomatic on machines without X11 (which cannot have `libGL.so` but still can have `libOpenGL.so`)
=> CMake: On non-Apple unix, use find_package for OpenGL

src/main.cpp
This is a patch submitted to FreeBSD bygzilla by @clausecker amd it should fix build on arm.
I don't personally think it's a correct solution, as unicode handling in bonzomatic is broken anyway (#169) and the original code seem to mix UTF codepoints, wchar_t and key codes which are all different things. But it definitely doesn't make things worse and fixing the build is a good thing.
=> Fix build on arm

CMakeLists.txt
I'm on an apple "silicon" computer and I don't want to install "Rosetta" because it's crap.
With this change, depending on the architecture you'll get a x86_64 or arm64 binary, which solves "my problem".
Let me know what you think.
=> use x86_64 or arm64 on macOS
